# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-27 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_coupon_couponrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='beli',
            field=models.IntegerField(default=1000),
        ),
    ]
